### ISSUE TITLE
ActivityNet Data Errors

### ISSUE THREAD

**Issue by gmvincent** [Qualcomm-AI-research/FrameExit#7]
I have followed the data structure format for how to store the data:
`The data for both datasets should be structured as follows:
            
            |--path_frame 
              |--video1_name
                |frame_name_0001.jpeg
                |frame_name_0002.jpeg
                 .
              |--video2_name
                |frame_name_0001.jpeg
                |frame_name_0002.jpeg`
Further, I have downloaded the annotations as outlined in the `inference.py`. 
I have verified I am working in an environment with proper requirements.

There still appear to be errors within the `inference.py` specifically in the` VideoLoader` in `dataset.py`.  The one I am running into now deals with the transforms:
```
python inference.py config/activitynet_inference_2d.yml
Loading config @ 'config/activitynet_inference_2d.yml'
127
Model loaded from: activitynet_checkpoint_25gmac.pth
v_1PQiq8zajCE
Traceback (most recent call last):
  File "inference.py", line 151, in <module>
    fire.Fire(inference)
  File "/home/gvincent/anaconda3/envs/frameexit/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/gvincent/anaconda3/envs/frameexit/lib/python3.6/site-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/home/gvincent/anaconda3/envs/frameexit/lib/python3.6/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "inference.py", line 106, in inference
    for itr, batch in enumerate(dataloader):
  File "/home/gvincent/anaconda3/envs/frameexit/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/gvincent/anaconda3/envs/frameexit/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/gvincent/anaconda3/envs/frameexit/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/gvincent/accelerator/FrameExit/dataset/dataset.py", line 119, in __getitem__
    clip = self.transform_spatial(clip)
  File "/home/gvincent/anaconda3/envs/frameexit/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 70, in __call__
    img = t(img)
  File "/home/gvincent/accelerator/FrameExit/dataset/transform.py", line 212, in __call__
    transformed = [self.transform(frame) for frame in frames]
TypeError: 'NoneType' object is not iterable
```

**Comment by aghodrati** [comment]
Hello, We suspect that there is an issue with loading the frames. Could you please debug your code on line 212 of dataset/transform.py to see if the frames are empty or if they have been properly loaded?

**Comment by gmvincent** [comment]
The above error arose as there was no return statement in the `__call__(self, frames)` function of the `ApplyImageTransform()` class. So with the defined list of transforms, nothing was returned after one transform was executed. 

Further errors are now arising within the labels of the dataset. The labels are given as str values but the transforms for activitynet seem to assume a numeric value. Given the following line from the `MultiHotEmbedding` class (line 320 of the following error message)
`return torch.zeros(self.num_classes).scatter(
            0, torch.tensor(label, dtype=torch.long), torch.tensor(1)
        )`

**My current error is:**
```['Throwing darts']
Traceback (most recent call last):
  File "inference.py", line 151, in <module>
    fire.Fire(inference)
  File "/home/gvincent/anaconda3/envs/frameexit/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/gvincent/anaconda3/envs/frameexit/lib/python3.6/site-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/home/gvincent/anaconda3/envs/frameexit/lib/python3.6/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "inference.py", line 106, in inference
    for itr, batch in enumerate(dataloader):
  File "/home/gvincent/anaconda3/envs/frameexit/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/gvincent/anaconda3/envs/frameexit/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/gvincent/anaconda3/envs/frameexit/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/gvincent/accelerator/FrameExit/dataset/dataset.py", line 124, in __getitem__
    label, metadata = self.__getitem_label__(frame_list, video_name)
  File "/home/gvincent/accelerator/FrameExit/dataset/dataset.py", line 104, in __getitem_label__
    labels = self.transform_label(labels)
  File "/home/gvincent/anaconda3/envs/frameexit/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 70, in __call__
    img = t(img)
  File "/home/gvincent/accelerator/FrameExit/dataset/transform.py", line 213, in __call__
    transformed = [self.transform(frame) for frame in frames]
  File "/home/gvincent/accelerator/FrameExit/dataset/transform.py", line 213, in <listcomp>
    transformed = [self.transform(frame) for frame in frames]
  File "/home/gvincent/accelerator/FrameExit/dataset/transform.py", line 320, in __call__
    0, torch.tensor(label, dtype=torch.long), torch.tensor(1)
ValueError: too many dimensions 'str'
```

Is there another transform that should be used instead of MultiHotEmbeddings? i.e., should LabelMapping be used?

**Comment by gmvincent** [comment]
Was able to solve the above issue by incorporating LabelMapping. Added the following line to the config file
```
preprocessing_label:
    video_multihot_labels: ""
    mapping: _path_/_to_/classes.txt
    one_hot_encoding: 200
```
Then in transform.py, changed the `LabelMapping` class `__init__`  to
```
def __init__(self, mapping_path):
        # mapping_path corresponds to classes.txt
        self.mapper = {line.strip(): i for i, line in enumerate(open(mapping_path, "r"))}
```
